/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (20) [BusinessEntityID]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[TelephoneNumber]
      ,[TelephoneSpecialInstructions]
      ,[Street]
      ,[City]
      ,[StateProvince]
      ,[PostalCode]
      ,[CountryRegion]
      ,[HomeAddressSpecialInstructions]
      ,[EMailAddress]
      ,[EMailSpecialInstructions]
      ,[EMailTelephoneNumber]
      ,[rowguid]
      ,[ModifiedDate]
  FROM [AdventureWorks2019].[Person].[vAdditionalContactInfo]