ALTER TABLE Marks ADD CONSTRAINT FK_Professor_ID FOREIGN KEY(ProfessorFK) REFERENCES  Professor(id)
GO

ALTER TABLE Marks ADD CONSTRAINT FK_DisciplineFK_ID FOREIGN KEY(DisciplineFK) REFERENCES  Discipline(id)
GO

ALTER TABLE Marks ADD CONSTRAINT FK_StudBachelors_ID FOREIGN KEY(StudFK) REFERENCES  StudBachelors(id)
GO

ALTER TABLE Marks ADD CONSTRAINT FK_StudMags_ID FOREIGN KEY(StudFK) REFERENCES  StudMag(id)

SELECT * FROM Marks